spring:
  application:
    name: sukasa-air-plotline-application
    description: sukasa-air-plotline-application
    version: 1.0-SNAPSHOT
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /sukasa
  shutdown: graceful

logging:
  level:
    org:
      springframework:
        web: DEBUG

mongodb:
  uri: ${MONGODB_URI:mongodb+srv://user0001:CU8MZgdHfHzthk7E@cluster0.nwsacep.mongodb.net/}${MONGODB_DATABASE:sukasa_air_reservation}
  database: ${MONGODB_DATABASE:sukasa_air_reservation}
  admin: ${MONGODB_ADMIN_EMAIL:admin@sukasaair.com}

appConfig:
  jwtTokenExpiryInSeconds: ${JWT_TOKEN_EXPIRY_IN_SECONDS:300}